# Generated by Django 4.1.6 on 2023-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
