# Generated by Django 4.1.5 on 2023-02-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_image',
            field=models.ImageField(default='media/file/photos/OIP_1.png', upload_to='media/files/photos'),
        ),
    ]
