# Generated by Django 4.1.5 on 2023-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdata_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_image',
            field=models.ImageField(default='media/file/photos/OIP_1.png', upload_to='media/files/photos/user_<django.db.models.fields.related.ForeignKey>/product_<django.db.models.fields.UUIDField>/'),
        ),
    ]
