# Generated by Django 4.1.5 on 2023-02-09 06:25

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdata_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_image',
            field=models.ImageField(default='media/file/photos/OIP_1.png', upload_to=product.models.upload_to),
        ),
    ]
