# Generated by Django 4.1.5 on 2023-02-10 19:48

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(default='media/file/photos/OIP_1.png', upload_to=product.models.upload_to_user),
        ),
    ]
