# Generated by Django 4.1.5 on 2023-02-10 20:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to_user),
        ),
    ]
