# Generated by Django 4.1.5 on 2023-02-10 21:31

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(default='mysite\\static\\media\\media\x0ciles\\photos\x8079.png', upload_to=product.models.upload_to_user),
        ),
    ]
