# Generated by Django 4.1.5 on 2023-02-11 13:37

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_userdetails_about_userdetails_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_descrition',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(upload_to=product.models.upload_to_user),
        ),
    ]
