# Generated by Django 4.1.5 on 2023-02-11 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_productdata_product_descrition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Userimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='https://cdn-icons-png.flaticon.com/512/20/20079.png', upload_to=product.models.upload_to_user)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
