# Generated by Django 4.1.5 on 2023-02-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_image', models.ImageField(default='media/file/photos/OIP_1.jfif', upload_to='media/files/photos')),
            ],
        ),
    ]
